In [217]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

import pickle

In [218]:
df=pd.read_csv('Churn_Modelling.csv',)
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [219]:
df=df.drop(['RowNumber','CustomerId','Surname'], axis=1)

In [220]:
label_encode_gender=LabelEncoder()
df['Gender']=label_encode_gender.fit_transform(df['Gender'])
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [221]:
##onehotencoder
from sklearn.preprocessing import OneHotEncoder
One_hot=OneHotEncoder()
geo_encode=One_hot.fit_transform(df[['Geography']])
geo_encode.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [222]:
geo_encode_df=pd.DataFrame(geo_encode.toarray(),columns=One_hot.get_feature_names_out(['Geography'])
 )
geo_encode_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [223]:
df= pd.concat([df.drop('Geography' , axis=1),geo_encode_df],axis=1)
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [224]:
with open('label_encode_gender.pkl' ,'wb') as file:
   pickle.dump(label_encode_gender,file) 

with open('geo_encode.pkl' ,'wb') as file:
   pickle.dump(One_hot,file)

In [225]:
## now separating dependent and independent variables

X=df.drop(['EstimatedSalary'], axis =1) 
Y=df['EstimatedSalary']

In [226]:
X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size=0.2, random_state=42)

In [227]:
scalar=StandardScaler()
X_train= scalar.fit_transform(X_train)
X_test=scalar.transform(X_test)

In [228]:
with open("scalar.pkl","wb") as file:
  pickle.dump(scalar,file)

In [229]:
import tensorflow as tf 

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping , TensorBoard
import datetime

In [230]:
model=Sequential([
 Dense(64,activation='relu',input_shape=(X_train.shape[1],)),   ##hideen layer 1
 Dense(32,activation='relu'),##hidden layer 2
 Dense(1) ## output layer 

])

In [231]:
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_24 (Dense)            (None, 64)                832

 dense_25 (Dense)            (None, 32)                2080

 dense_26 (Dense)            (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [232]:

model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

In [233]:
##lets create log table 
logs_dir="regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensor_callback=TensorBoard(log_dir=logs_dir, histogram_freq=1)

In [234]:
Early_Stopping=EarlyStopping(monitor="val_loss",patience=10,restore_best_weights=True)

In [235]:
history=model.fit(
  X_train,Y_train,
  validation_data=(X_test,Y_test),
  epochs=100,
  callbacks=[tensor_callback,Early_Stopping]
)

Epoch 1/100
250/250 [==============================] - 2s 4ms/step - loss: 100373.6484 - mae: 100373.6484 - val_loss: 98502.4609 - val_mae: 98502.4609
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 99583.4609 - mae: 99583.4609 - val_loss: 96914.6250 - val_mae: 96914.6250
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 96826.8594 - mae: 96826.8594 - val_loss: 92870.6016 - val_mae: 92870.6016
Epoch 4/100
250/250 [==============================] - 1s 5ms/step - loss: 91451.3984 - mae: 91451.3984 - val_loss: 86183.4453 - val_mae: 86183.4453
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 83540.0312 - mae: 83540.0312 - val_loss: 77394.8672 - val_mae: 77394.8672
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 74242.5469 - mae: 74242.5469 - val_loss: 68361.8984 - val_mae: 68361.8984
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 65309.7969 - mae: 65309.7969 - val_loss: 60624.2031 - val_mae: 60624.2031
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 58411.3438 - mae: 58411.3438 - val_loss: 55329.8906 - val_mae: 55329.8906
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 54065.0312 - mae: 54065.0312 - val_loss: 52460.7344 - val_mae: 52460.7344
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 51873.1367 - mae: 51873.1367 - val_loss: 51293.2930 - val_mae: 51293.2930
Epoch 11/100
250/250 [==============================] - 1s 4ms/step - loss: 50925.4766 - mae: 50925.4766 - val_loss: 50916.0117 - val_mae: 50916.0117
Epoch 12/100
250/250 [==============================] - 1s 2ms/step - loss: 50558.6719 - mae: 50558.6719 - val_loss: 50798.1836 - val_mae: 50798.1836
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 50394.3984 - mae: 50394.3984 - val_loss: 50724.1172 - val_mae: 50724.1172
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 50294.6406 - mae: 50294.6406 - val_loss: 50674.6133 - val_mae: 50674.6133
Epoch 15/100
250/250 [==============================] - 1s 4ms/step - loss: 50216.3086 - mae: 50216.3086 - val_loss: 50620.4102 - val_mae: 50620.4102
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 50153.9023 - mae: 50153.9023 - val_loss: 50577.5039 - val_mae: 50577.5039
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 50097.6992 - mae: 50097.6992 - val_loss: 50547.4219 - val_mae: 50547.4219
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 50046.9922 - mae: 50046.9922 - val_loss: 50515.3008 - val_mae: 50515.3008
Epoch 19/100
250/250 [==============================] - 1s 4ms/step - loss: 50006.1836 - mae: 50006.1836 - val_loss: 50481.7617 - val_mae: 50481.7617
Epoch 20/100
250/250 [==============================] - 1s 4ms/step - loss: 49970.1953 - mae: 49970.1953 - val_loss: 50455.2227 - val_mae: 50455.2227
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 49934.6680 - mae: 49934.6680 - val_loss: 50440.4414 - val_mae: 50440.4414
Epoch 22/100
250/250 [==============================] - 1s 4ms/step - loss: 49903.6602 - mae: 49903.6602 - val_loss: 50419.4961 - val_mae: 50419.4961
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 49875.5000 - mae: 49875.5000 - val_loss: 50390.8672 - val_mae: 50390.8672
Epoch 24/100
250/250 [==============================] - 1s 4ms/step - loss: 49846.1445 - mae: 49846.1445 - val_loss: 50388.6250 - val_mae: 50388.6250
Epoch 25/100
250/250 [==============================] - 1s 5ms/step - loss: 49820.0547 - mae: 49820.0547 - val_loss: 50373.4531 - val_mae: 50373.4531
Epoch 26/100
250/250 [==============================] - 1s 5ms/step - loss: 49799.4766 - mae: 49799.4766 - val_loss: 50357.4570 - val_mae: 50357.4570
Epoch 27/100
250/250 [==============================] - 1s 5ms/step - loss: 49775.6445 - mae: 49775.6445 - val_loss: 50352.8984 - val_mae: 50352.8984
Epoch 28/100
250/250 [==============================] - 1s 3ms/step - loss: 49757.9062 - mae: 49757.9062 - val_loss: 50337.5547 - val_mae: 50337.5547
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 49737.8164 - mae: 49737.8164 - val_loss: 50317.0117 - val_mae: 50317.0117
Epoch 30/100
250/250 [==============================] - 1s 4ms/step - loss: 49716.5938 - mae: 49716.5938 - val_loss: 50311.5781 - val_mae: 50311.5781
Epoch 31/100
250/250 [==============================] - 1s 4ms/step - loss: 49701.1133 - mae: 49701.1133 - val_loss: 50297.9453 - val_mae: 50297.9453
Epoch 32/100
250/250 [==============================] - 1s 4ms/step - loss: 49685.5625 - mae: 49685.5625 - val_loss: 50293.2383 - val_mae: 50293.2383
Epoch 33/100
250/250 [==============================] - 1s 4ms/step - loss: 49667.3398 - mae: 49667.3398 - val_loss: 50287.8008 - val_mae: 50287.8008
Epoch 34/100
250/250 [==============================] - 1s 4ms/step - loss: 49652.3438 - mae: 49652.3438 - val_loss: 50279.8789 - val_mae: 50279.8789
Epoch 35/100
250/250 [==============================] - 1s 4ms/step - loss: 49638.8945 - mae: 49638.8945 - val_loss: 50298.7734 - val_mae: 50298.7734
Epoch 36/100
250/250 [==============================] - 1s 5ms/step - loss: 49625.7773 - mae: 49625.7773 - val_loss: 50299.1445 - val_mae: 50299.1445
Epoch 37/100
250/250 [==============================] - 1s 5ms/step - loss: 49614.5859 - mae: 49614.5859 - val_loss: 50290.5078 - val_mae: 50290.5078
Epoch 38/100
250/250 [==============================] - 1s 5ms/step - loss: 49603.1680 - mae: 49603.1680 - val_loss: 50292.9102 - val_mae: 50292.9102
Epoch 39/100
250/250 [==============================] - 1s 4ms/step - loss: 49594.1602 - mae: 49594.1602 - val_loss: 50284.9453 - val_mae: 50284.9453
Epoch 40/100
250/250 [==============================] - 1s 4ms/step - loss: 49580.2695 - mae: 49580.2695 - val_loss: 50285.6250 - val_mae: 50285.6250
Epoch 41/100
250/250 [==============================] - 1s 4ms/step - loss: 49568.4492 - mae: 49568.4492 - val_loss: 50269.3125 - val_mae: 50269.3125
Epoch 42/100
250/250 [==============================] - 1s 3ms/step - loss: 49560.0664 - mae: 49560.0664 - val_loss: 50266.3086 - val_mae: 50266.3086
Epoch 43/100
250/250 [==============================] - 1s 4ms/step - loss: 49550.8242 - mae: 49550.8242 - val_loss: 50267.7617 - val_mae: 50267.7617
Epoch 44/100
250/250 [==============================] - 1s 3ms/step - loss: 49540.3164 - mae: 49540.3164 - val_loss: 50264.8516 - val_mae: 50264.8516
Epoch 45/100
250/250 [==============================] - 1s 4ms/step - loss: 49532.1133 - mae: 49532.1133 - val_loss: 50271.6445 - val_mae: 50271.6445
Epoch 46/100
250/250 [==============================] - 1s 3ms/step - loss: 49522.6875 - mae: 49522.6875 - val_loss: 50256.5898 - val_mae: 50256.5898
Epoch 47/100
250/250 [==============================] - 1s 4ms/step - loss: 49514.3516 - mae: 49514.3516 - val_loss: 50265.4336 - val_mae: 50265.4336
Epoch 48/100
250/250 [==============================] - 1s 6ms/step - loss: 49506.2617 - mae: 49506.2617 - val_loss: 50264.4297 - val_mae: 50264.4297
Epoch 49/100
250/250 [==============================] - 1s 3ms/step - loss: 49506.3672 - mae: 49506.3672 - val_loss: 50265.3828 - val_mae: 50265.3828
Epoch 50/100
250/250 [==============================] - 1s 4ms/step - loss: 49492.0625 - mae: 49492.0625 - val_loss: 50271.2422 - val_mae: 50271.2422
Epoch 51/100
250/250 [==============================] - 1s 5ms/step - loss: 49482.9141 - mae: 49482.9141 - val_loss: 50267.5469 - val_mae: 50267.5469
Epoch 52/100
250/250 [==============================] - 1s 5ms/step - loss: 49475.2852 - mae: 49475.2852 - val_loss: 50264.1797 - val_mae: 50264.1797
Epoch 53/100
250/250 [==============================] - 3s 11ms/step - loss: 49469.3438 - mae: 49469.3438 - val_loss: 50255.1094 - val_mae: 50255.1094
Epoch 54/100
250/250 [==============================] - 2s 9ms/step - loss: 49463.5078 - mae: 49463.5078 - val_loss: 50255.5938 - val_mae: 50255.5938
Epoch 55/100
250/250 [==============================] - 2s 7ms/step - loss: 49457.7305 - mae: 49457.7305 - val_loss: 50260.7031 - val_mae: 50260.7031
Epoch 56/100
250/250 [==============================] - 2s 6ms/step - loss: 49456.1055 - mae: 49456.1055 - val_loss: 50263.6250 - val_mae: 50263.6250
Epoch 57/100
250/250 [==============================] - 2s 7ms/step - loss: 49443.9727 - mae: 49443.9727 - val_loss: 50270.0469 - val_mae: 50270.0469
Epoch 58/100
250/250 [==============================] - 2s 7ms/step - loss: 49440.6797 - mae: 49440.6797 - val_loss: 50279.9609 - val_mae: 50279.9609
Epoch 59/100
250/250 [==============================] - 2s 8ms/step - loss: 49432.9883 - mae: 49432.9883 - val_loss: 50264.2734 - val_mae: 50264.2734
Epoch 60/100
250/250 [==============================] - 2s 7ms/step - loss: 49428.8125 - mae: 49428.8125 - val_loss: 50259.8438 - val_mae: 50259.8438
Epoch 61/100
250/250 [==============================] - 2s 8ms/step - loss: 49423.1992 - mae: 49423.1992 - val_loss: 50276.9570 - val_mae: 50276.9570
Epoch 62/100
250/250 [==============================] - 2s 7ms/step - loss: 49417.7539 - mae: 49417.7539 - val_loss: 50279.3203 - val_mae: 50279.3203
Epoch 63/100
250/250 [==============================] - 2s 7ms/step - loss: 49411.9531 - mae: 49411.9531 - val_loss: 50282.7695 - val_mae: 50282.7695

In [236]:
model.save('model.h6')

INFO:tensorflow:Assets written to: model.h6\assets

INFO:tensorflow:Assets written to: model.h6\assets

In [237]:
import numpy as np 
from tensorflow.keras.models import load_model

In [238]:
model = load_model('model.h6')